import { StyleSheet } from "react-native";

export const cores = {
  fundo: "#F4F7FB",
  superficie: "#FFFFFF",
  primaria: "#2563EB",
  primariaEscura: "#1D4ED8",
  texto: "#172033",
  textoSecundario: "#667085",
  borda: "#E4E7EC",
  sucesso: "#16A34A",
  aviso: "#F59E0B",
  perigo: "#DC2626",
};

const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: cores.fundo,
  },
  safeArea: {
    flex: 1,
    backgroundColor: cores.fundo,
  },
  container: {
    flex: 1,
    width: "100%",
    backgroundColor: cores.fundo,
  },
  content: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 28,
  },
  hero: {
    marginBottom: 22,
  },
  eyebrow: {
    color: cores.primaria,
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 7,
  },
  title: {
    color: cores.texto,
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: -0.7,
  },
  subtitle: {
    color: cores.textoSecundario,
    fontSize: 16,
    lineHeight: 23,
    marginTop: 8,
  },
  menuGrid: {
    gap: 12,
  },
  menuCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: cores.superficie,
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 18,
    padding: 16,
  },
  menuCardPressed: {
    opacity: 0.72,
    transform: [{ scale: 0.99 }],
  },
  menuIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF6FF",
    marginRight: 14,
  },
  menuText: {
    flex: 1,
  },
  menuTitle: {
    color: cores.texto,
    fontSize: 17,
    fontWeight: "700",
  },
  menuDescription: {
    color: cores.textoSecundario,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  screenHeader: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: cores.superficie,
    borderWidth: 1,
    borderColor: cores.borda,
  },
  screenHeaderText: {
    flex: 1,
  },
  screenTitle: {
    color: cores.texto,
    fontSize: 22,
    fontWeight: "800",
  },
  screenSubtitle: {
    color: cores.textoSecundario,
    fontSize: 13,
    marginTop: 2,
  },
  listContent: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingBottom: 24,
    gap: 10,
  },
  itemCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: cores.superficie,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: cores.borda,
    padding: 15,
  },
  itemNumber: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#EFF6FF",
    color: cores.primaria,
    textAlign: "center",
    textAlignVertical: "center",
    fontWeight: "800",
    marginRight: 12,
  },
  item: {
    color: cores.texto,
    fontSize: 16,
    fontWeight: "600",
  },
  sectionHeader: {
    color: cores.texto,
    fontSize: 18,
    fontWeight: "800",
    backgroundColor: cores.fundo,
    paddingTop: 16,
    paddingBottom: 8,
  },
  sectionItem: {
    backgroundColor: cores.superficie,
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
  },
  sectionItemText: {
    color: cores.texto,
    fontSize: 15,
    fontWeight: "600",
  },
  scrollContent: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingBottom: 28,
  },
  scrollItem: {
    backgroundColor: cores.superficie,
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 14,
    padding: 15,
    marginBottom: 9,
  },
  carouselContainer: {
    flex: 1,
  },
  carouselViewport: {
    flex: 1,
  },
  page: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  carouselCard: {
    width: "88%",
    maxWidth: 520,
    minHeight: 260,
    borderRadius: 28,
    padding: 28,
    justifyContent: "flex-end",
  },
  carouselTag: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.22)",
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    marginBottom: 14,
  },
  carouselTitle: {
    color: "#FFFFFF",
    fontSize: 30,
    fontWeight: "800",
  },
  carouselText: {
    color: "rgba(255,255,255,0.88)",
    fontSize: 15,
    lineHeight: 21,
    marginTop: 8,
  },
  dots: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 7,
    marginVertical: 18,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#D0D5DD",
  },
  dotActive: {
    width: 24,
    backgroundColor: cores.primaria,
  },
  dashboardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  statCard: {
    minWidth: "46%",
    flexGrow: 1,
    backgroundColor: cores.superficie,
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 18,
    padding: 16,
  },
  statLabel: {
    color: cores.textoSecundario,
    fontSize: 13,
    fontWeight: "600",
  },
  statValue: {
    color: cores.texto,
    fontSize: 26,
    fontWeight: "800",
    marginTop: 5,
  },
  panel: {
    backgroundColor: cores.superficie,
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 18,
    padding: 16,
    marginTop: 14,
  },
  panelTitle: {
    color: cores.texto,
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 12,
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: "#EAECF0",
    overflow: "hidden",
  },
  progressFill: {
    width: "68%",
    height: "100%",
    backgroundColor: cores.primaria,
    borderRadius: 999,
  },
  formGroup: {
    marginBottom: 14,
  },
  label: {
    color: cores.texto,
    fontWeight: "700",
    fontSize: 14,
    marginBottom: 7,
  },
  input: {
    backgroundColor: cores.superficie,
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 14,
    minHeight: 50,
    paddingHorizontal: 14,
    color: cores.texto,
    fontSize: 15,
  },
  primaryButton: {
    minHeight: 50,
    backgroundColor: cores.primaria,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  primaryButtonPressed: {
    backgroundColor: cores.primariaEscura,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 15,
  },
  resultBox: {
    marginTop: 16,
    backgroundColor: "#ECFDF3",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#ABEFC6",
  },
  resultText: {
    color: "#067647",
    fontSize: 14,
    lineHeight: 20,
  },
});

export default styles;
